# Generated by Django 5.0.1 on 2026-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='acu',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acu',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='acu',
            name='school',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='acu',
            name='stream',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
