# Generated by Django 5.0.1 on 2026-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0003_acu_age_acu_gender_acu_school_acu_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
