# Generated by Django 5.0.1 on 2026-04-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0004_message_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
